version: 2.1
orbs:
  slack: circleci/slack@4.1
executors:
  my-executor:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /home/circleci/project 
jobs:
  checkout-code:
    executor: my-executor
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0f:b3:05:30:eb:c4:f7:0d:aa:1e:9d:ff:e4:ad:ee:28"
      - run: pwd && ls -la
      - checkout
      - run: pwd && ls -la
      - persist_to_workspace:
          root: /home/circleci/
          paths:
          - project
      - run: ls -la /home/circleci/project 
  build:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/circleci/project
      - run: pwd && cd /home/circleci/project
      - run:
          name: List all content from source code
          command: pwd && ls -la
      - run:
          name: Install dependencies
          command: mvn dependency:go-offline        
      - run:
          name: Validate
          command: mvn -B validate
      - run:
          name: Compile
          command: mvn -B compile                
      - run:
          name: Test
          command: mvn test
      - run:
          name: Check code coverage
          command: mvn clean test
      - run:
          name: Install
          command: mvn clean install
      - run:
          name: Validate WAR file
          command: pwd && ls -la ./target && chmod 755 ./target/api.war    
      - run:
          name: Deploy to tomcat server over SSH
          command: |
            ls -la ./target
            scp -o "StrictHostKeyChecking=no" ./target/api.war ubuntu@ec2-54-151-223-91.ap-southeast-1.compute.amazonaws.com:/tmp
            ssh -o "StrictHostKeyChecking=no" ubuntu@ec2-54-151-223-91.ap-southeast-1.compute.amazonaws.com "sudo mv /tmp/api.war /opt/tomcat/webapps/ && pwd && sudo ls -la /opt/tomcat/webapps/"
      - run:
          name: Deploy artifact to nexus
          command: |
            curl -u admin:fptproject -X GET 'http://13.215.61.77:8081/service/rest/v1/components?repository=test'
            curl -v -u admin:fptproject -X POST 'http://13.215.61.77:8081/service/rest/v1/components?repository=store-artifact' -F maven2.groupId=com.google.guava -F maven2.artifactId=guava -F maven2.version=24.0-jre -F maven2.asset1=/home/circleci/project/target/api.war -F maven2.asset1.extension=war
      - slack/notify:
          event: fail
          channel: $SLACK_DEFAULT_CHANNEL
          template: basic_fail_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: success_tagged_deploy_1
workflows:
  checkout-code-and-build:
    jobs:
      - checkout-code:
          filters:
            branches:
              only: sit
      - build:
          requires:
            - checkout-code
          filters:
            branches:
              only: sit
#Test

